action_id: trunk-share-with-everyone
date: 2025-08-19 07:24:13
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1755588253
full_timestamp:
  nanos: 394457000
  seconds: 1755588253
trunk_version: 1.25.0
